routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::resource('posts', 'FrontController', ['only' => ['show', 'index']]);
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'cabinet', 'middleware' => ['auth']], function () {
    Route::match(['get'], '/pages', 'PageController@anyData')->name('list');
    Route::match(['post'], '/upload', 'PageController@upload');
    Route::resource('page', 'PageController');
});

app/Http/Controllers/FrontController.php
<?php


namespace App\Http\Controllers;


use App\Contracts\PostsContract;
use App\Values\Posts\PostsId;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FrontController
{
    private $posts;
    private $request;
    private $user;

    public function __construct(PostsContract $postsContract, Request $request)
    {
        $this->posts = $postsContract;
        $this->request = $request;
        $this->user = Auth::user();
    }

    public function index()
    {
        return view('front.main')->with(
            ['articles' => $this->posts->getList(
                "*",
                $take = 9
            )]);

    }

    public function show(int $id)
    {
        $id = PostsId::new($id);
        return view('front.detail')->with(['post' => $this->posts->getOne($id)]);
    }
}

resources/views/front/detail.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/vendor/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/vendor/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/vendor/Ionicons/css/ionicons.min.css') }}">
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('/css/main.css') }}">


</head>
<body>


<div class="row">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="container">
                <div class="col-md-12">
                    <div class="page-header">
                        <h1 class="title">{{$post->title()->value()}} </h1>
                    </div>
                    <img src="/upload/{{$post->picture}}" class="img-responsive">
                    <hr class="">
                    <div class="col-md-12">
                    <?php     $trimmed = trim($post->content, '"');
                    echo $trimmed;?>
                    </div>
                    <div class="pull-right" style="margin-top: 35px">
                        <hr>
                    <div>{{$post->created_at}}</div>
                    <div>{{$post->authorRelation->name}}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

resources/views/front/main.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/vendor/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/vendor/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/vendor/Ionicons/css/ionicons.min.css') }}">
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('/css/main.css') }}">


</head>
<body>

<div class="content">
    <div class="col-md-12" style="margin: 0 auto">
        @if($articles)
            <div class="panel panel-default">
                <div class="jumbotron">
                    <h1>Blog</h1>
                    <p>For young and energy peope</p>
                </div>
                <div class="row">
                    <div class="center-block">
                        @foreach($articles as $article)
                            <div class="col-md-5" style="max-width: 500px">
                                <div class="thumbnail article-list" style="max-width: 550px">
                                    <div class="view view-first"
                                    ">
                                    <img src={{ asset("/upload/".$article->picture)}}  class="img-responsive">
                                    <div class="mask">
                                        <h2 style="margin-top: 10%;color: #fff ">{{  Str::limit($article->title,50) }}</h2>
                                        <p>{{  $article->created_at }}</p>

                                        <a href="{{route('posts.show',['id'=>$article->id])}}" class="info">
                                            Подробнее </a>
                                    </div>

                                </div>
                                <div class="caption"><a
                                            href="{{route('posts.show',['id'=>$article->id])}}">{{  Str::limit($article->title,50) }}</a>
                                </div>
                            </div>
                    </div>
                    @endforeach
                </div>
                <div class="content">
                    <div class="col-md-12">
                        <ul class="pagination">
                            @if($articles->lastPage() > 1)
                                @if($articles->currentPage() !== 1)
                                    <li class="active"></li>
                                    <li><a href="{{ $articles->url(($articles->currentPage() - 1)) }}">&laquo;</a></li>

                                @endif
                                @for($i = 1; $i <= $articles->lastPage(); $i++)
                                    @if($articles->currentPage() == $i)
                                        <li><a class="selected disabled">{{ $i }}</a></li>
                                    @else
                                        <li><a href="{{ $articles->url($i) }}">{{ $i }}</a></li>
                                    @endif
                                @endfor
                                @if($articles->currentPage() !== $articles->lastPage())
                                    <li><a href="{{ $articles->url(($articles->currentPage() + 1)) }}">&raquo;</a></li>
                                @endif
                            @endif
                        </ul>
                        @endif
                    </div>
                </div>

            </div>
    </div>
</div>
</div>
</body>
</html>